/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PoliticaDeTrocasRouteImport } from './routes/politica-de-trocas'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as EntregasRouteImport } from './routes/entregas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeTrocasRoute = PoliticaDeTrocasRouteImport.update({
  id: '/politica-de-trocas',
  path: '/politica-de-trocas',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasRoute = EntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/entregas': typeof EntregasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/entregas': typeof EntregasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/entregas': typeof EntregasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/entregas'
    | '/politica-de-privacidade'
    | '/politica-de-trocas'
    | '/termos-de-uso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/entregas'
    | '/politica-de-privacidade'
    | '/politica-de-trocas'
    | '/termos-de-uso'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/entregas'
    | '/politica-de-privacidade'
    | '/politica-de-trocas'
    | '/termos-de-uso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EntregasRoute: typeof EntregasRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticaDeTrocasRoute: typeof PoliticaDeTrocasRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-trocas': {
      id: '/politica-de-trocas'
      path: '/politica-de-trocas'
      fullPath: '/politica-de-trocas'
      preLoaderRoute: typeof PoliticaDeTrocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas': {
      id: '/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof EntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EntregasRoute: EntregasRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticaDeTrocasRoute: PoliticaDeTrocasRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
